# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sysinfo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsysinfo.proto\x12\tSIPackage\"x\n\x06Status\x12\x0f\n\x02ip\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x10\n\x03\x63pu\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x02\x88\x01\x01\x12\x13\n\x06momery\x18\x04 \x01(\x05H\x03\x88\x01\x01\x42\x05\n\x03_ipB\x06\n\x04_cpuB\x08\n\x06_emailB\t\n\x07_momeryb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sysinfo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=28
  _STATUS._serialized_end=148
# @@protoc_insertion_point(module_scope)
